MODEL:
  #META_ARCHITECTURE: "GeneralizedRCNN"

  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    STEM_FUNC: "StemWithNotFixedBatchNorm_deepsz1"
    TRANS_FUNC: "BottleneckWithFixedBatchNorm"
  BACKBONE:
    CONV_BODY: "R-50-C4"

SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
