MODEL:
  #META_ARCHITECTURE: "GeneralizedRCNN"

  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    STEM_FUNC: "StemWithNotFixedBatchNorm_deepsz1"
    TRANS_FUNC: "BottleneckWithNoFixedBatchNorm"
  BACKBONE:
    CONV_BODY: "R-50-C4"
    FREEZE_CONV_BODY_AT: -1

SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.002
  STEPS: (1000, 4000)
  MAX_ITER: 30000
  #WARMUP_METHOD: 'warmup_reset_per_epoch'
  #WARMUP_METHOD: 'linear'
  #WARMUP_ITERS: 400
OUTPUT_DIR: "/media/zhen/Research/deepsz_pytorch/"
